services:
  db:
    image: mysql:8.0
    container_name: monbudget-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: monbudget
      MYSQL_USER: monbudget
      MYSQL_PASSWORD: monbudget
    ports:
      - "3306:3306"
    volumes:
      - monbudget_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  monbudget_data:
