# ==============================================
# DOCKER COMPOSE - PRODUCTION
# Mon Budget API - Configuration sécurisée
# ==============================================

version: '3.8'

services:
  # Application Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-api-prod
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://budget_user:${POSTGRES_PASSWORD}@db:5432/budget_production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES=15m
      - JWT_REFRESH_EXPIRES=7d
      - BCRYPT_SALT_ROUNDS=12
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - budget-network
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: budget-postgres-prod
    restart: unless-stopped
    environment:
      - POSTGRES_DB=budget_production
      - POSTGRES_USER=budget_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backup:/backup
    ports:
      - "127.0.0.1:5432:5432"  # Bind uniquement sur localhost
    networks:
      - budget-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budget_production"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Reverse Proxy Nginx
  nginx:
    image: nginx:alpine
    container_name: budget-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - budget-network
    security_opt:
      - no-new-privileges:true

  # Service de backup automatique
  backup:
    image: mysql:8.0
    container_name: budget-backup-prod
    restart: "no"
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./backup:/backup
      - ./scripts/backup.sh:/backup.sh:ro
    networks:
      - budget-network
    depends_on:
      - db
    command: ["sh", "/backup.sh"]
    profiles:
      - backup

  # Monitoring avec Watchtower (mises à jour automatiques)
  watchtower:
    image: containrrr/watchtower
    container_name: budget-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400  # 24h
      - WATCHTOWER_INCLUDE_STOPPED=true
    networks:
      - budget-network
    profiles:
      - monitoring

networks:
  budget-network:
    driver: bridge
    name: budget-prod-network

volumes:
  postgres-data:
    driver: local
    name: budget-postgres-data
  app-logs:
    driver: local
    name: budget-app-logs
  nginx-logs:
    driver: local
    name: budget-nginx-logs